# Generated by Django 3.0.8 on 2020-07-28 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eficiencia', '0001_initial'),
        ('evento', '0001_initial'),
        ('tear', '0002_auto_20200728_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eficiencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eficiencia.Eficiencia')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evento.Evento')),
                ('tear', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tear.Tear')),
            ],
            options={
                'verbose_name_plural': '01 - Lançamentos',
            },
        ),
    ]
