# Generated by Django 3.0.8 on 2020-07-29 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0002_auto_20200729_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lancamentos',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lancamentos',
            name='updated_at',
        ),
    ]
