# Generated by Django 3.0.8 on 2020-07-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0003_auto_20200729_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentos',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
