# Generated by Django 3.0.8 on 2020-07-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0004_lancamentos_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentos',
            name='hora',
            field=models.TimeField(null=True),
        ),
    ]
