# Generated by Django 3.0.8 on 2020-07-28 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tear', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tear',
            options={'verbose_name_plural': '01 - Cadastro de Tear'},
        ),
    ]
